# Generated by Django 3.0.14 on 2021-10-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0005_delete_role'),
        ('user', '0003_auto_20211022_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matces',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_name', models.CharField(default='', max_length=255)),
                ('venue', models.CharField(default='', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MatcesUserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matces.Matces')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='MatcesTeamDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Team')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matces.Matces')),
            ],
        ),
        migrations.AddField(
            model_name='matces',
            name='team',
            field=models.ManyToManyField(through='matces.MatcesTeamDetails', to='team.Team'),
        ),
        migrations.AddField(
            model_name='matces',
            name='user',
            field=models.ManyToManyField(through='matces.MatcesUserDetails', to='user.User'),
        ),
    ]
