# Generated by Django 3.0.14 on 2021-10-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matcesteamdetails',
            name='team_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matcesuserdetails',
            name='user_score',
            field=models.IntegerField(default=0),
        ),
    ]
