# Generated by Django 3.0.14 on 2021-10-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_delete_role'),
        ('matces', '0002_auto_20211022_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matcesteamdetails',
            old_name='Team',
            new_name='team',
        ),
        migrations.AlterUniqueTogether(
            name='matcesteamdetails',
            unique_together={('team', 'match')},
        ),
    ]
