# Generated by Django 3.0.14 on 2021-10-22 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20211021_2156'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
