# Generated by Django 3.0.14 on 2021-10-22 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211022_0934'),
        ('team', '0004_delete_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
